version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      safe:
        patterns: ["*"]
        update-types: ["minor", "patch"]
