com.pentaho|pentaho-ee-parent-pom=11.1.0.0-233
com.pentaho|pentaho-ee-jar-parent-pom=11.1.0.0-233
com.pentaho|pentaho-ee-bundle-parent-pom=11.1.0.0-233
org.pentaho|pentaho-parent-pom=11.1.0.0-233
org.pentaho|pentaho-ce-parent-pom=11.1.0.0-233
org.pentaho|pentaho-ce-jar-parent-pom=11.1.0.0-233
org.pentaho|pentaho-ce-bundle-parent-pom=11.1.0.0-233
org.pentaho.di.plugins|pdi-plugins=11.1.0.0-233
com.pentaho.di.plugins|pdi-ee-plugins=11.1.0.0-233

ael.version=11.1.0.0-233
aggdesigner.version=11.1.0.0-233
analysis-ee-plugin.version=11.1.0.0-233
analyzer-plugin.version=11.1.0.0-233
archetypes.version=11.1.0.0-233
big-data-plugin.version=11.1.0.0-233
big-data-kafka-plugin.version=11.1.0.0-233
coding-standards.version=11.1.0.0-233
common-ui.version=11.1.0.0-233
commons-database.version=11.1.0.0-233
commons-ee.version=11.1.0.0-233
commons-gwt.version=11.1.0.0-233
commons-xul.version=11.1.0.0-233
container-utils.version=11.1.0.0-233
dashboard.version=11.1.0.0-233
dashboard-plugin.version=11.1.0.0-233
encryption-support.version=11.1.0.0-233
jdbc-distribution-utility.version=11.1.0.0-233
kafka-plugin.version=11.1.0.0-233
launcher.version=11.1.0.0-233
layout-editor.version=11.1.0.0-233
metadata-client-tool.version=11.1.0.0-233
metastore.version=11.1.0.0-233
mondrian.version=11.1.0.0-233
mondrian-schemaworkbench-plugins.version=11.1.0.0-233
oss-licenses.version=11.1.0.0-233
pdi-data-refinery-plugin.version=11.1.0.0-233
pdi-dataservice-client-plugin.version=11.1.0.0-233
pdi-dataservice-plugin.version=11.1.0.0-233
pdi-google-analytics-plugin-ce.version=11.1.0.0-233
pdi-google-analytics-plugin.version=11.1.0.0-233
pdi-hadoop-plugin-ee.version=11.1.0.0-233
pdi-jms-plugin.version=11.1.0.0-233
pdi-monitoring-plugin.version=11.1.0.0-233
pdi-osgi-bridge.version=11.1.0.0-233
pdi-platform-utils-plugin.version=11.1.0.0-233
pdi-plugins-ee.version=11.1.0.0-233
pdi-pur-plugin.version=11.1.0.0-233
pdi-salesforce-plugin.version=11.1.0.0-233
pdi-sap-hana-bulk-loader-plugin.version=11.1.0.0-233
pdi-scheduler-plugin.version=11.1.0.0-233
pdi-spark-plugin.version=11.1.0.0-233
pdi-teradata-tpt-plugin.version=11.1.0.0-233
pdi-weka-plugin-group.version=11.1.0.0-233
pdi-json-plugin.version=11.1.0.0-233
pdi-r-plugin.version=11.1.0.0-233
pdi-sap-plugin.version=11.1.0.0-233
pdi-sdk-plugins.version=11.1.0.0-233
pdi-xml-plugin.version=11.1.0.0-233
pdi.version=11.1.0.0-233
pentaho-actionsequence-dom.version=11.1.0.0-233
pentaho-camel.version=11.1.0.0-233
pentaho-cassandra-plugin.version=11.1.0.0-233
pentaho-ccc-plugin.version=11.1.0.0-233
pentaho-cda-plugin.version=11.1.0.0-233
pentaho-cde-plugin.version=11.1.0.0-233
pentaho-cdf-plugin.version=11.1.0.0-233
pentaho-cgg-plugin.version=11.1.0.0-233
pentaho-chartbeans.version=11.1.0.0-233
pentaho-connections.version=11.1.0.0-233
pentaho-cpf-plugin.version=11.1.0.0-233
pentaho-cpk-plugin.version=11.1.0.0-233
pentaho-dashboard-chart-editor.version=11.1.0.0-233
pentaho-data-access.version=11.1.0.0-233
pentaho-data-mining.version=11.1.0.0-233
pentaho-det.version=11.1.0.0-233
pentaho-ee-chart-plugin.version=11.1.0.0-233
pentaho-ee-dsc.version=11.1.0.0-233
pentaho-ee-license-installer.version=11.1.0.0-233
pentaho-eula-wrap-config.version=11.1.0.0-233
pentaho-geo-plugin.version=11.1.0.0-233
pentaho-hadoop-shims.version=11.1.0.0-233
pentaho-hadoop-shims-api.version=11.1.0.0-233
pentaho-hadoop-shims-cdh513.version=11.1.0.0-233
pentaho-hadoop-shims-cdh514.version=11.1.0.0-233
pentaho-hadoop-shims-cdh61.version=11.1.0.0-233
pentaho-hadoop-shims-cdpdc71.version=11.1.0.0-233
pentaho-hadoop-shims-dataproc1421.version=11.1.0.0-233
pentaho-hadoop-shims-emr511.version=11.1.0.0-233
pentaho-hadoop-shims-emr521.version=11.1.0.0-233
pentaho-hadoop-shims-hdp26.version=11.1.0.0-233
pentaho-hadoop-shims-hdp30.version=11.1.0.0-233
pentaho-hadoop-shims-mapr520.version=11.1.0.0-233
pentaho-hadoop-shims-mapr60.version=11.1.0.0-233
pentaho-hadoop-shims-mapr61.version=11.1.0.0-233
pentaho-hadoop-shims-hdi40.version=11.1.0.0-233
pentaho-hdfs-vfs.version=11.1.0.0-233
pentaho-jpivot-plugin.version=11.1.0.0-233
pentaho-json.version=11.1.0.0-233
pentaho-kettle-yarn-plugin.version=11.1.0.0-233
pentaho-karaf.version=11.1.0.0-233
pentaho-launcher.version=11.1.0.0-233
pentaho-marketplace-modules.version=11.1.0.0-233
pentaho-metadata.version=11.1.0.0-233
pentaho-metastore.version=11.1.0.0-233
pentaho-metaverse.version=11.1.0.0-233
pentaho-modeler.version=11.1.0.0-233
pentaho-mongo-utils.version=11.1.0.0-233
pentaho-mongodb-plugin.version=11.1.0.0-233
pentaho-mql-editor.version=11.1.0.0-233
pentaho-operations-mart.version=11.1.0.0-233
pentaho-osgi-bundles.version=11.1.0.0-233
pentaho-palo-core.version=11.1.0.0-233
pentaho-pdi-ee-plugin.version=11.1.0.0-233
pentaho-pdi-plugin.version=11.1.0.0-233
pentaho-r-plugin.version=11.1.0.0-233
pentaho-registry.version=11.1.0.0-233
pentaho-report-wizard-core.version=11.1.0.0-233
pentaho-reporting-plugin.version=11.1.0.0-233
pentaho-reporting.version=11.1.0.0-233
pentaho-repository.version=11.1.0.0-233
pentaho-s3-vfs.version=11.1.0.0-233
pentaho-sparkl-plugin.version=11.1.0.0-233
pentaho-splunk-plugin.version=11.1.0.0-233
pentaho-versionchecker.version=11.1.0.0-233
pentaho-vfs-browser.version=11.1.0.0-233
pentaho.version=11.1.0.0-233
pir-plugin.version=11.1.0.0-233
platform.version=11.1.0.0-233
schemaworkbench-plugins.version=11.1.0.0-233
vertica-bulkloader-plugin.version=11.1.0.0-233
worker-nodes.version=11.1.0.0-233
worker-nodes-custom-resources.version=11.1.0.0-233
hierarchical-plugin-ee.version=11.1.0.0-233

docker.image.tag=9.3-latest
pentaho-cwm.version=1.5.4
pentaho-ofc4j.version=1.1.0
proguard.version=7.1.0
weka-jri.version=5.1.0

version-merger.version=1.0.9