name: Pentaho Connection Merge Workflow

on:
  push:
    branches:
      - semantic-versioned
    paths-ignore:
      - ".github/**"
      - "**.md"
  workflow_dispatch:
    inputs:
      base_version:
        required: false
        description: "The base version to use for the merge."
      skip_tests:
        type: boolean
        default: false
        description: "Skip Maven tests by adding -DskipTests."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTORY_BASE_URL: https://${{ vars.ARTIFACTORY_HOST }}/artifactory

jobs:
  reusable-merge-workflow:
    uses: pentaho/actions-common/.github/workflows/merge.yml@stable
    with:
      base_version: ${{ inputs.base_version }}
      modules_to_build: "."
      run_release_candidate: true
      use_semver_release_candidate: true
      additional_mvn_directives: ${{ github.event_name == 'workflow_dispatch' && inputs.skip_tests && '-Drelease -DskipTests' || '-Drelease' }}
      additional_snapshot_mvn_directives: ${{ github.event_name == 'workflow_dispatch' && inputs.skip_tests && '-DskipTests' || '' }}
    secrets: inherit

