# The GitHub Actions Workflow for Pull Requests in the main branch
#

name: pentaho-connections Pull Request workflow
on:
  pull_request:
    branches: [ "semantic-versioned" ]

jobs:
  reusable-pr-workflow:
    uses: pentaho/actions-common/.github/workflows/pr.yml@stable
    secrets: inherit